version: "3.9"

services:
  go-app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    environment:
      - CONFIG_PATH=config.yml
      - HTTP_SERVER_ADDRESS=0.0.0.0:8081
      - SALT_HASH=d2h4u1NJ0GF3fdJl
      - JWT_SIGNING=sf54dvlDkJzp9aKv5bH
      - DB_PASSWORD=hesoyam321!
      - REDIS_PASSWORD=hesoyam321!
    depends_on:
      - ns-postgres
      - ns-redis

  ns-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hesoyam321!
      POSTGRES_DB: notes

  ns-redis:
    image: redis:latest
    ports:
      - "6379:6379"