http_server:
  address: "0.0.0.0:8081"
  read_timeout: 20s
  write_timeout: 20s
  max_header_bytes: 1048576

grpc_server:
  address: "0.0.0.0:8082"

grpc_gateway:
  address: "0.0.0.0:8083"
  read_timeout: 20s
  write_timeout: 20s
  max_header_bytes: 1048576