data_base:
  host: "localhost"
  port: "5432"
  username: "admin"
  dbname: "notes"
  sslmode: "disable"
  driver: "pgx"

redis:
  address: "0.0.0.0:32768"
  db: 0

http_server:
  address: "localhost:8081"
  read_timeout: 20s
  write_timeout: 20s
  max_header_bytes: 1048576

grpc_server:
  address: "localhost:8082"

grpc_gateway:
  address: "localhost:8083"


migrations_dir: "../internal/db/migrations/"
#salt_hash: "d2h4u1NJ0GF3fdJl"
#jwt_signing: "sf54dvlDkJzp9aKv5bH"
#db_password: "hesoyam321!"
#redis_password: ""