data_base:
  host: "0.0.0.0"
  port: "5432"
  username: "admin"
  dbname: "notes"
  sslmode: "disable"
  driver: "pgx"

redis:
  address: "0.0.0.0:6379"
  db: 0

http_server:
  address: "localhost:8081"
  read_timeout: 20s
  write_timeout: 20s
  max_header_bytes: 1048576

grpc_server:
  address: "localhost:8082"

grpc_gateway:
  address: "localhost:8083"
  read_timeout: 20s
  write_timeout: 20s
  max_header_bytes: 1048576


migrations_dir: "../internal/db/migrations/"
#SALT_HASH: "d2h4u1NJ0GF3fdJl"
#JWT_SIGNING: "sf54dvlDkJzp9aKv5bH"
#DB_PASSWORD: "hesoyam321!"
#REDIS_PASSWORD: ""