db:
  host: "localhost"
  port: "5432"
  username:
  password:
  dbname: "bookmarks"
  sslmode: "disable"
  driver: "pgx"

server:
    port: "8086"

salt: "b8a8be5c69248224cmv" # в переменную окружения

session: "20215131194292347011640767887127245" # в переменную окружения
